Lists

In [5]:
# Lists are mutable arrays

names = ["Nguyen", "Minh", "Nghia"]

In [2]:
# Index into list by index
print(names[0])

Nguyen


In [6]:
# Append to list (append to end of list)
names.append("Hust")
print(names)

['Nguyen', 'Minh', 'Nghia', 'Hust']


In [7]:
# Get length of list
print(len(names))

4


In [8]:
# Concate two lists
names += ["Bach", "Khoa"]
print(names)

['Nguyen', 'Minh', 'Nghia', 'Hust', 'Bach', 'Khoa']


In [9]:
# Two ways create an empty list
more_names = []
more_names = list()

In [10]:
stuff = [1, ["hello", "bye"], -0.25, None]
print(stuff)

[1, ['hello', 'bye'], -0.25, None]


In [11]:
numbers = [0,1,2,3,4,5,6]

# Slices from start index (inclusive) to end index (exclusive)
print(numbers[0:3])

[0, 1, 2]


In [12]:
# When start index is not specified, it is start of list
print(numbers[:3])

# When end index is not specified, it is end of list
print(numbers[3:])

[0, 1, 2]
[3, 4, 5, 6]


In [13]:
# : takes the slice of all elements along a dimension, is very useful when working with numpy arrays
print(numbers[:])

[0, 1, 2, 3, 4, 5, 6]


In [14]:
# Negative index wraps around, start counting from the end of list
print(numbers[-1])
print(numbers[-3:])
print(numbers[3:-2])

6
[4, 5, 6]
[3, 4]


Tuples

In [15]:
# Tuple are immutable arrays

# Use parenthese for tuples, square brackets for lists
tuples = ("Bach", "Khoa")

In [16]:
# Syntax for accessing an element and getting length are the same as lists
print(tuples[0])
print(len(tuples))

Bach
2


In [18]:
# But unlike lists, tuples do not support item re-assignment
tuples[0] = "Change"

'Khoa'

In [19]:
# Create an empty tuples
empty = tuple()
print(empty)

# Create a tuple with a single item, the comma is important
single = (10,)
print(single)

()
(10,)


Dictionary

In [ ]:
# Dictionary are hash maps

# Two ways to create an empty dictionary
phonebook = {}
phonebook = dict()

In [20]:
# Create dictionary with one item
phonebook = {"Nguyen": "984"}
# Add another item
phonebook["Minh"] = "324"

In [22]:
# Check if a key is in the dictionary
print("Nguyen" in phonebook)
print("Nghia" in phonebook)

True
False


In [23]:
#Get corresponding value for a key
print(phonebook["Nguyen"])

984


In [24]:
# Delete an item
del phonebook["Minh"]
print(phonebook)

{'Nguyen': '984'}


Loops

In [25]:
# Basic for loop
for i in range(5):
    print(i)

0
1
2
3
4


In [26]:
#To iterate over a list
for name in names:
    print(name)

Nguyen
Minh
Nghia
Hust
Bach
Khoa


In [31]:
# To iterate over indices and values in a list
# Way 1
for i in range(len(names)):
    print(i, names[i])

print("------------")

# Way 2
for i,name in enumerate(names):
    print(i, name)

0 Nguyen
1 Minh
2 Nghia
3 Hust
4 Bach
5 Khoa
------------
0 Nguyen
1 Minh
2 Nghia
3 Hust
4 Bach
5 Khoa


In [33]:
# To iterate over a dictionary
phonebook = {"Nguyen": "984", "Minh": "324", "Nghia": "294" }

# Iterate over keys
for name in phonebook:
    print(name)

print("----------------")

# Iterate over values
for number in phonebook.values():
    print(number)
    
print("----------------")

# Iterate over keys and values
for name, number in phonebook.items():
    print(name, number)

Nguyen
Minh
Nghia
----------------
984
324
294
----------------
Nguyen 984
Minh 324
Nghia 294


Numpy

In [1]:
import numpy as np

In [4]:
x = np.array([1,2,3])
y = np.array([[3,4,5]])
z = np.array([[6,7],[8,9]])

print(x.shape)
print(y.shape)
print()
print(z)
print(z.shape)

(3,)
(1, 3)

[[6 7]
 [8 9]]
(2, 2)


In [10]:
a = np.arange(10)
b = a.reshape((5,2))
print(a)
print()
print(b)

[0 1 2 3 4 5 6 7 8 9]

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)
print()
print(x.shape)

[[1 2]
 [3 4]
 [5 6]]

(3, 2)


In [17]:
print(np.max(x, axis=1))

[2 4 6]


In [18]:
print((np.max(x, axis=1)).shape)

(3,)


In [21]:
print(np.max(x, axis=1, keepdims=True))

[[2]
 [4]
 [6]]


In [22]:
print(np.max(x, axis=1, keepdims=True).shape)

(3, 1)


In [23]:
A = np.array([[1,2], [3,4]])
B = np.array([[3,3], [3,3]])
print(A)
print(B)
print()
print(A*B)

[[1 2]
 [3 4]]
[[3 3]
 [3 3]]

[[ 3  6]
 [ 9 12]]


In [24]:
# One way to do matrix multiplication
print(np.matmul(A,B))

# Another way
print(A @ B)

[[ 9  9]
 [21 21]]
[[ 9  9]
 [21 21]]


In [26]:
u = np.array([1,2,3])
v = np.array([1,10,100])

print(np.dot(u,v))
print(u.dot(v))

321
321


In [27]:
W = np.array([[1,2], [3,4], [5,6]])
print(v.shape)
print(W.shape)

print(np.dot(v, W))
print(np.dot(v,W).shape)

(3,)
(3, 2)
[531 642]
(2,)


In [31]:
x = np.random.random((3,4))

# Selects all of x
print(x[:])

[[0.1799263  0.72359976 0.32706893 0.93575254]
 [0.01969727 0.78499656 0.76276258 0.94024791]
 [0.2709661  0.48442704 0.19746639 0.49001666]]


In [37]:
# Selects the 0th and 2nd rows
print(x[np.array([0,2]), :])
print()

# Selects 1st row as 1-D vector and 1st through 2nd elements
print(x[1, 1:3])

[[0.1799263  0.72359976 0.32706893 0.93575254]
 [0.2709661  0.48442704 0.19746639 0.49001666]]

[0.78499656 0.76276258]


In [39]:
# Boolean indexing
print(x[x>0.8])

[0.93575254 0.94024791]


In [40]:
# 3-D vector of shape (3,4,1)
print(x[:,:,np.newaxis])

[[[0.1799263 ]
  [0.72359976]
  [0.32706893]
  [0.93575254]]

 [[0.01969727]
  [0.78499656]
  [0.76276258]
  [0.94024791]]

 [[0.2709661 ]
  [0.48442704]
  [0.19746639]
  [0.49001666]]]


Broadcasting

In [42]:
x = np.random.random((3,4))
y = np.random.random((3,1))
z = np.random.random((1,4))

s = x+y
p = x*z

In [44]:
print(x.shape)
print(y.shape)
print(s.shape)

(3, 4)

(3, 1)
(3, 4)


In [49]:
a = np.zeros((3,3))
b = np.array([[1,2,3]])
print(a)
print()
print(a+b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [50]:
a = np.random.random((3,4))
b = np.random.random((3,1))
c = np.random.random((3,))

In [51]:
result1 = b + b.T

print(b.shape)
print(b.T.shape)
print(result1.shape)
print(result1)

(3, 1)
(1, 3)
(3, 3)
[[0.30794496 0.66393448 1.12537078]
 [0.66393448 1.01992399 1.4813603 ]
 [1.12537078 1.4813603  1.9427966 ]]


In [54]:
result2 = b + a

print(b.shape)
print(a.shape)
print(result2.shape)
print(result2)

(3, 1)
(3, 4)
(3, 4)
[[0.87822746 0.17467823 0.2045999  0.98572511]
 [1.02363286 0.66233147 1.14625449 0.80347154]
 [1.15990156 1.21134717 1.19707039 1.92252569]]


Efficient NumPy Code

In [55]:
%%timeit
x = np.random.rand(1000,1000)
for i in range(100,1000):
    for j in range(x.shape[1]):
        x[i,j]+=5

332 ms ± 29.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
%%timeit
x = np.random.rand(1000,1000)
x[np.arange(100,1000), :] +=5

20.4 ms ± 2.66 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
